# Patch generated by Pyment v0.3.3

--- a/..//venv/lib/python3.8/site-packages/numpy/tests/test_scripts.py
+++ b/..//venv/lib/python3.8/site-packages/numpy/tests/test_scripts.py
@@ -15,6 +15,7 @@
 
 
 def find_f2py_commands():
+    """ """
     if sys.platform == 'win32':
         exe_dir = dirname(sys.executable)
         if exe_dir.endswith('Scripts'): # virtualenv
@@ -36,11 +37,23 @@
 @pytest.mark.xfail(reason="Test is unreliable")
 @pytest.mark.parametrize('f2py_cmd', find_f2py_commands())
 def test_f2py(f2py_cmd):
+    """
+
+    Parameters
+    ----------
+    f2py_cmd :
+        
+
+    Returns
+    -------
+
+    """
     # test that we can run f2py script
     stdout = subprocess.check_output([f2py_cmd, '-v'])
     assert_equal(stdout.strip(), b'2')
 
 
 def test_pep338():
+    """ """
     stdout = subprocess.check_output([sys.executable, '-mnumpy.f2py', '-v'])
     assert_equal(stdout.strip(), b'2')
