# Patch generated by Pyment v0.3.3

--- a/..//venv/lib/python3.8/site-packages/pandas/tests/dtypes/cast/test_construct_object_arr.py
+++ b/..//venv/lib/python3.8/site-packages/pandas/tests/dtypes/cast/test_construct_object_arr.py
@@ -6,6 +6,19 @@
 @pytest.mark.parametrize("datum1", [1, 2.0, "3", (4, 5), [6, 7], None])
 @pytest.mark.parametrize("datum2", [8, 9.0, "10", (11, 12), [13, 14], None])
 def test_cast_1d_array(datum1, datum2):
+    """
+
+    Parameters
+    ----------
+    datum1 :
+        
+    datum2 :
+        
+
+    Returns
+    -------
+
+    """
     data = [datum1, datum2]
     result = construct_1d_object_array_from_listlike(data)
 
@@ -16,5 +29,16 @@
 
 @pytest.mark.parametrize("val", [1, 2.0, None])
 def test_cast_1d_array_invalid_scalar(val):
+    """
+
+    Parameters
+    ----------
+    val :
+        
+
+    Returns
+    -------
+
+    """
     with pytest.raises(TypeError, match="has no len()"):
         construct_1d_object_array_from_listlike(val)
