# Patch generated by Pyment v0.3.3

--- a/..//venv/lib/python3.8/site-packages/pandas/tests/indexing/multiindex/test_chaining_and_caching.py
+++ b/..//venv/lib/python3.8/site-packages/pandas/tests/indexing/multiindex/test_chaining_and_caching.py
@@ -7,6 +7,7 @@
 
 
 def test_detect_chained_assignment():
+    """ """
     # Inplace ops, originally from:
     # https://stackoverflow.com/questions/20508968/series-fillna-in-a-multiindex-dataframe-does-not-fill-is-this-a-bug
     a = [12, 23]
@@ -29,6 +30,7 @@
 
 
 def test_cache_updating():
+    """ """
     # 5216
     # make sure that we don't try to set a dead cache
     a = np.random.rand(10, 3)
@@ -50,6 +52,7 @@
 
 
 def test_indexer_caching():
+    """ """
     # GH5727
     # make sure that indexers are in the _internal_names_set
     n = 1000001
