# Patch generated by Pyment v0.3.3

--- a/..//venv/lib/python3.8/site-packages/pandas/tests/test_errors.py
+++ b/..//venv/lib/python3.8/site-packages/pandas/tests/test_errors.py
@@ -22,6 +22,17 @@
     ],
 )
 def test_exception_importable(exc):
+    """
+
+    Parameters
+    ----------
+    exc :
+        
+
+    Returns
+    -------
+
+    """
     from pandas import errors
 
     err = getattr(errors, exc)
@@ -36,6 +47,7 @@
 
 
 def test_catch_oob():
+    """ """
     from pandas import errors
 
     msg = "Out of bounds nanosecond timestamp: 1500-01-01 00:00:00"
@@ -44,19 +56,24 @@
 
 
 class Foo:
+    """ """
     @classmethod
     def classmethod(cls):
+        """ """
         raise AbstractMethodError(cls, methodtype="classmethod")
 
     @property
     def property(self):
+        """ """
         raise AbstractMethodError(self, methodtype="property")
 
     def method(self):
+        """ """
         raise AbstractMethodError(self)
 
 
 def test_AbstractMethodError_classmethod():
+    """ """
     xpr = "This classmethod must be defined in the concrete class Foo"
     with pytest.raises(AbstractMethodError, match=xpr):
         Foo.classmethod()
